/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpanel;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author PC
 */
public class UnosTrenera extends javax.swing.JPanel {

    /**
     * Creates new form UnosTrenera
     */
    public UnosTrenera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxtJmbg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jBtnSacuvaj = new javax.swing.JButton();
        jTxtDatum = new javax.swing.JTextField();
        jTxtLicenca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtIme = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTxtPrezime = new javax.swing.JTextField();

        setBackground(new java.awt.Color(11, 60, 93));

        jLabel2.setForeground(new java.awt.Color(217, 179, 16));
        jLabel2.setText("Prezime");

        jLabel3.setForeground(new java.awt.Color(217, 179, 16));
        jLabel3.setText("Datum rodjenja");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(217, 179, 16));
        jLabel8.setText("Unos trenera");

        jTxtJmbg.setBackground(new java.awt.Color(50, 140, 193));

        jLabel4.setForeground(new java.awt.Color(217, 179, 16));
        jLabel4.setText("Jmbg");

        jBtnSacuvaj.setText("Sacuvaj");

        jTxtDatum.setBackground(new java.awt.Color(50, 140, 193));

        jTxtLicenca.setBackground(new java.awt.Color(50, 140, 193));

        jLabel6.setForeground(new java.awt.Color(217, 179, 16));
        jLabel6.setText("Licenca:");

        jTxtIme.setBackground(new java.awt.Color(50, 140, 193));

        jLabel1.setForeground(new java.awt.Color(217, 179, 16));
        jLabel1.setText("Ime");

        jTxtPrezime.setBackground(new java.awt.Color(50, 140, 193));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jTxtLicenca, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jTxtDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jTxtJmbg, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jTxtPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jTxtIme, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtLicenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getjTxtIme() {
        return jTxtIme;
    }

    public JButton getjBtnSacuvaj() {
        return jBtnSacuvaj;
    }

    public JTextField getjTxtDatum() {
        return jTxtDatum;
    }

    public JTextField getjTxtJmbg() {
        return jTxtJmbg;
    }

    public JTextField getjTxtLicenca() {
        return jTxtLicenca;
    }

    public JTextField getjTxtPrezime() {
        return jTxtPrezime;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTxtDatum;
    private javax.swing.JTextField jTxtIme;
    private javax.swing.JTextField jTxtJmbg;
    private javax.swing.JTextField jTxtLicenca;
    private javax.swing.JTextField jTxtPrezime;
    // End of variables declaration//GEN-END:variables
}
